//
// Generated file, do not edit! Created by opp_msgtool 6.1 from packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class GlobalIn;
class DownloadIn;
class UploadIn;
class GlobalDOut;
class DownloadDOut;
class UploadDOut;
class DownloadReduce;
class UploadReduce;
/**
 * Class generated from <tt>packet.msg:1</tt> by opp_msgtool.
 * <pre>
 * packet GlobalIn
 * {
 *     int inId;
 *     int bId;
 * }
 * </pre>
 */
class GlobalIn : public ::omnetpp::cPacket
{
  protected:
    int inId = 0;
    int bId = 0;

  private:
    void copy(const GlobalIn& other);

  protected:
    bool operator==(const GlobalIn&) = delete;

  public:
    GlobalIn(const char *name=nullptr, short kind=0);
    GlobalIn(const GlobalIn& other);
    virtual ~GlobalIn();
    GlobalIn& operator=(const GlobalIn& other);
    virtual GlobalIn *dup() const override {return new GlobalIn(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getInId() const;
    virtual void setInId(int inId);

    virtual int getBId() const;
    virtual void setBId(int bId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GlobalIn& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GlobalIn& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet.msg:5</tt> by opp_msgtool.
 * <pre>
 * packet DownloadIn
 * {
 *     int inId;
 *     int bId;
 * }
 * </pre>
 */
class DownloadIn : public ::omnetpp::cPacket
{
  protected:
    int inId = 0;
    int bId = 0;

  private:
    void copy(const DownloadIn& other);

  protected:
    bool operator==(const DownloadIn&) = delete;

  public:
    DownloadIn(const char *name=nullptr, short kind=0);
    DownloadIn(const DownloadIn& other);
    virtual ~DownloadIn();
    DownloadIn& operator=(const DownloadIn& other);
    virtual DownloadIn *dup() const override {return new DownloadIn(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getInId() const;
    virtual void setInId(int inId);

    virtual int getBId() const;
    virtual void setBId(int bId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DownloadIn& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DownloadIn& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet.msg:9</tt> by opp_msgtool.
 * <pre>
 * packet UploadIn
 * {
 *     int inId;
 *     int bId;
 * }
 * </pre>
 */
class UploadIn : public ::omnetpp::cPacket
{
  protected:
    int inId = 0;
    int bId = 0;

  private:
    void copy(const UploadIn& other);

  protected:
    bool operator==(const UploadIn&) = delete;

  public:
    UploadIn(const char *name=nullptr, short kind=0);
    UploadIn(const UploadIn& other);
    virtual ~UploadIn();
    UploadIn& operator=(const UploadIn& other);
    virtual UploadIn *dup() const override {return new UploadIn(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getInId() const;
    virtual void setInId(int inId);

    virtual int getBId() const;
    virtual void setBId(int bId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UploadIn& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UploadIn& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet.msg:14</tt> by opp_msgtool.
 * <pre>
 * packet GlobalDOut
 * {
 *     int inId;
 *     int bId;
 * }
 * </pre>
 */
class GlobalDOut : public ::omnetpp::cPacket
{
  protected:
    int inId = 0;
    int bId = 0;

  private:
    void copy(const GlobalDOut& other);

  protected:
    bool operator==(const GlobalDOut&) = delete;

  public:
    GlobalDOut(const char *name=nullptr, short kind=0);
    GlobalDOut(const GlobalDOut& other);
    virtual ~GlobalDOut();
    GlobalDOut& operator=(const GlobalDOut& other);
    virtual GlobalDOut *dup() const override {return new GlobalDOut(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getInId() const;
    virtual void setInId(int inId);

    virtual int getBId() const;
    virtual void setBId(int bId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const GlobalDOut& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, GlobalDOut& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet.msg:19</tt> by opp_msgtool.
 * <pre>
 * packet DownloadDOut
 * {
 *     int inId;
 *     int bId;
 * }
 * </pre>
 */
class DownloadDOut : public ::omnetpp::cPacket
{
  protected:
    int inId = 0;
    int bId = 0;

  private:
    void copy(const DownloadDOut& other);

  protected:
    bool operator==(const DownloadDOut&) = delete;

  public:
    DownloadDOut(const char *name=nullptr, short kind=0);
    DownloadDOut(const DownloadDOut& other);
    virtual ~DownloadDOut();
    DownloadDOut& operator=(const DownloadDOut& other);
    virtual DownloadDOut *dup() const override {return new DownloadDOut(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getInId() const;
    virtual void setInId(int inId);

    virtual int getBId() const;
    virtual void setBId(int bId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DownloadDOut& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DownloadDOut& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet.msg:23</tt> by opp_msgtool.
 * <pre>
 * packet UploadDOut
 * {
 *     int inId;
 *     int bId;
 * }
 * </pre>
 */
class UploadDOut : public ::omnetpp::cPacket
{
  protected:
    int inId = 0;
    int bId = 0;

  private:
    void copy(const UploadDOut& other);

  protected:
    bool operator==(const UploadDOut&) = delete;

  public:
    UploadDOut(const char *name=nullptr, short kind=0);
    UploadDOut(const UploadDOut& other);
    virtual ~UploadDOut();
    UploadDOut& operator=(const UploadDOut& other);
    virtual UploadDOut *dup() const override {return new UploadDOut(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getInId() const;
    virtual void setInId(int inId);

    virtual int getBId() const;
    virtual void setBId(int bId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UploadDOut& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UploadDOut& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet.msg:28</tt> by opp_msgtool.
 * <pre>
 * packet DownloadReduce
 * {
 *     int bId;
 * }
 * </pre>
 */
class DownloadReduce : public ::omnetpp::cPacket
{
  protected:
    int bId = 0;

  private:
    void copy(const DownloadReduce& other);

  protected:
    bool operator==(const DownloadReduce&) = delete;

  public:
    DownloadReduce(const char *name=nullptr, short kind=0);
    DownloadReduce(const DownloadReduce& other);
    virtual ~DownloadReduce();
    DownloadReduce& operator=(const DownloadReduce& other);
    virtual DownloadReduce *dup() const override {return new DownloadReduce(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getBId() const;
    virtual void setBId(int bId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DownloadReduce& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DownloadReduce& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>packet.msg:32</tt> by opp_msgtool.
 * <pre>
 * packet UploadReduce
 * {
 *     int bId;
 * }
 * </pre>
 */
class UploadReduce : public ::omnetpp::cPacket
{
  protected:
    int bId = 0;

  private:
    void copy(const UploadReduce& other);

  protected:
    bool operator==(const UploadReduce&) = delete;

  public:
    UploadReduce(const char *name=nullptr, short kind=0);
    UploadReduce(const UploadReduce& other);
    virtual ~UploadReduce();
    UploadReduce& operator=(const UploadReduce& other);
    virtual UploadReduce *dup() const override {return new UploadReduce(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getBId() const;
    virtual void setBId(int bId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const UploadReduce& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, UploadReduce& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline GlobalIn *fromAnyPtr(any_ptr ptr) { return check_and_cast<GlobalIn*>(ptr.get<cObject>()); }
template<> inline DownloadIn *fromAnyPtr(any_ptr ptr) { return check_and_cast<DownloadIn*>(ptr.get<cObject>()); }
template<> inline UploadIn *fromAnyPtr(any_ptr ptr) { return check_and_cast<UploadIn*>(ptr.get<cObject>()); }
template<> inline GlobalDOut *fromAnyPtr(any_ptr ptr) { return check_and_cast<GlobalDOut*>(ptr.get<cObject>()); }
template<> inline DownloadDOut *fromAnyPtr(any_ptr ptr) { return check_and_cast<DownloadDOut*>(ptr.get<cObject>()); }
template<> inline UploadDOut *fromAnyPtr(any_ptr ptr) { return check_and_cast<UploadDOut*>(ptr.get<cObject>()); }
template<> inline DownloadReduce *fromAnyPtr(any_ptr ptr) { return check_and_cast<DownloadReduce*>(ptr.get<cObject>()); }
template<> inline UploadReduce *fromAnyPtr(any_ptr ptr) { return check_and_cast<UploadReduce*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PACKET_M_H

